services:
  client:
    image : 2am_client
    container_name: client
    build:
      context: ./client
    ports:
      - "5173:5173"
  server:
    image: 2am_server
    container_name: server
    build:
      context: ./server
    ports:
      - "3002:3001"
